# Generated by Django 4.2.2 on 2023-06-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(default='Action'),
        ),
    ]
