# Generated by Django 4.2.2 on 2023-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_movie_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seating',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
    ]
