# Generated by Django 4.2.2 on 2023-06-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.TextField()),
                ('seats', models.TextField()),
                ('name', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='seating',
            name='movie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.movie'),
        ),
    ]
