# Generated by Django 4.2.2 on 2023-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_transactionrecord_seating_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='total',
            field=models.IntegerField(),
        ),
    ]
