# Generated by Django 4.2.2 on 2023-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_transactionrecord_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
