# Generated by Django 4.2.2 on 2023-07-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_transactionrecord_id_transactionrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='current_fund',
            field=models.IntegerField(default=0),
        ),
    ]
